# Generated by Django 3.2.3 on 2021-05-31 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_products_category', '0001_initial'),
        ('novinfajr_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catgory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novinfajr_products_category.productcategory'),
        ),
    ]
