# Generated by Django 3.2.3 on 2021-05-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_products', '0002_product_catgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgory',
            new_name='category',
        ),
    ]
