# Generated by Django 3.2.3 on 2021-05-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='تخصصص')),
                ('comment', models.TextField(verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
