# Generated by Django 3.2.3 on 2021-05-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_client_comment', '0003_alter_clientcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='تصویر'),
        ),
    ]
