# Generated by Django 3.2.3 on 2021-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='products/category', verbose_name='تصویر'),
        ),
    ]
