# Generated by Django 3.2.3 on 2021-05-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_products', '0001_initial'),
        ('novinfajr_order', '0002_alter_order_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novinfajr_order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novinfajr_products.product')),
            ],
        ),
    ]
