# Generated by Django 3.2.3 on 2021-06-03 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novinfajr_order', '0004_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
            preserve_default=False,
        ),
    ]
